name: Tests

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Compiles the app but not upload artifacts to distribution server'
        default: false
        required: false
        type: boolean

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  pypi:
    permissions:
      contents: write # Allows this job to create releases

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.11"]
        os: [macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Installer Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Vérifier installation Node.js
        run: npm -v

      - name: Installer PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest


      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: pdm install

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Installer dépendances
        run: pdm install --no-interaction --no-root
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Installer la librairie
        run: pdm install --no-interaction

      - name: Configurer mot de passe
        run: pdm config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"

      - name: Publier sur PyPI
        if: ${{ !inputs.dry-run }}
        run: pdm publish --build

