name: Tests

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Compiles the app but not upload artifacts to distribution server'
        default: false
        required: false
        type: boolean

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  pypi:
    permissions:
      contents: write # Allows this job to create releases

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Installer Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Installer dépendances
        run: pdm install

      - name: Publier sur PyPI
        if: ${{ !inputs.dry-run }}
        run: pdm publish
