name: Tests

on: [ workflow_call ]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.11"]
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Installer Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Vérifier installation Node.js
        run: npm -v

      - name: Installer PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: pdm install

      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Tests simples
        run: pdm cov --log-cli-level=DEBUG && pdm run coverage xml

      - name: Tests complets
        env:
          VRAI_SERVEUR: 1
        run: pdm cov --log-cli-level=DEBUG && pdm run coverage xml
        
      - name: Envoyer rapports de couverture à Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
